In [4]:
import numpy as np 
path = "/Users/ashleyturner/Development/imperial/msc_research_project/unet_abc/results/gibbs_with_table_2025-08-08T09:28:53Z/"
samples = np.load(path+"posterior_samples.npy")
scores = np.load(path+"posterior_scores.npy")

print(samples)
print(scores)

[[[0.01274289]
  [0.02485777]
  [0.17982344]
  [0.05124668]
  [0.499044  ]]

 [[0.06763756]
  [0.05471124]
  [0.0408575 ]
  [0.04399269]
  [0.34290895]]

 [[0.039443  ]
  [0.10316598]
  [0.08562337]
  [0.18798663]
  [0.26163068]]

 [[0.08656878]
  [0.07970735]
  [0.13939993]
  [0.19275165]
  [0.26705727]]

 [[0.04266002]
  [0.09281933]
  [0.11503381]
  [0.15672995]
  [0.36866498]]

 [[0.02238824]
  [0.1651881 ]
  [0.07510511]
  [0.08244747]
  [0.38623786]]

 [[0.05607499]
  [0.12915476]
  [0.11469642]
  [0.14514983]
  [0.2702382 ]]

 [[0.05344495]
  [0.05019258]
  [0.13732077]
  [0.145923  ]
  [0.37805504]]

 [[0.04427053]
  [0.11586916]
  [0.17598322]
  [0.1330989 ]
  [0.41650257]]

 [[0.0329736 ]
  [0.08761209]
  [0.10678321]
  [0.17262955]
  [0.35190955]]

 [[0.00686191]
  [0.04140468]
  [0.05169371]
  [0.2837195 ]
  [0.4635633 ]]

 [[0.00417305]
  [0.14190446]
  [0.28714067]
  [0.24799934]
  [0.2527743 ]]

 [[0.00384587]
  [0.13206685]
  [0.16744816]
  [0.25870326]
  [0.19635537]]
